---
- include: db_to_host_mapping.yml

- hosts: "all:&{{ hostvars['localhost']['db_mapping']['host']}}"
  roles:
    - role: db-maintenance
      db_action: 'startup'

    - role: db-maintenance
      db_action: 'shutdown'
